FROM ubuntu:latest
MAINTAINER adamr <adamr@catalyst-au.net>

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
RUN echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
RUN apt-get update &&\
    apt-get install -y mongodb-org=3.0.4 mongodb-org-server=3.0.4 mongodb-org-shell=3.0.4 mongodb-org-mongos=3.0.4 mongodb-org-tools=3.0.4

EXPOSE 27017

VOLUME /var/log/mongodb
RUN mkdir -p /data/db
VOLUME /data/db

CMD ["/usr/bin/mongod"]
